language: php

sudo: false

php: 
  - 7.1
  - 7.2
  - 7.3
  - 7.4
    
before_install:  
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --dev --no-suggest --no-interaction

before_script:
  - export XDEBUG_MODE=coverage

script:
 - vendor/bin/phpunit --version
 - mkdir -p build/logs

after_script:
 - travis_retry vendor/bin/php-coveralls -v
